import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
// @ts-ignore
import {attributes, react as HomeContent} from '../content/home.md'
import Script from 'next/script'

const Home: NextPage = () => {
    let {title, cats} = attributes;
    return (
        <div className={styles.container}>
            <Head>
                <title>{title} - Blog</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Script src="https://identity.netlify.com/v1/netlify-identity-widget.js"/>
            <article>
                <h1 className="text-3xl font-bold underline">{title}</h1>
                <HomeContent/>
                <ul>
                    {cats.map((cat: { name: string; description: string }, k: string) => (
                        <li key={k}>
                            <h2>{cat.name}</h2>
                            <p>{cat.description}</p>
                        </li>
                    ))}
                </ul>
            </article>
        </div>
    )
}

export default Home
